[[main]]
  name = "Documentation"
  pageRef = "/docs/key-features"
  weight = 10

[[main]]
  name = "Install"
  pageRef = "/docs/operations/install"
  weight = 20

[[main]]
  name = "PHP client"
  url = "https://github.com/tamarackdb/tamarackdb-php"
  weight = 30

[[main]]
  name = "Search"
  weight = 40
  [main.params]
    type = "search"

[[main]]
  name = "GitHub"
  url = "https://github.com/tamarackdb/tamarackdb"
  weight = 50
  [main.params]
    icon = "github"
