title = "TamarackDB"
baseurl = "http://localhost/"
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "term"]
enableGitInfo = false
enableRobotsTXT = true
locale = "en-US"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[outputs]
  home = ["HTML", "llms", "llmsfull"]
  section = ["HTML"]
  page = ["HTML"]

[outputFormats.llmsfull]
  baseName = "llms-full"
  isHTML = false
  isPlainText = true
  mediaType = "text/plain"

[permalinks]
  docs = "/docs/:sections[1:]/:slug/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
