description = "Event store in pure Go, compliant with the DCB specification, accessible via HTTP, using SQLite as the storage engine."

[navbar]
  displayTitle = false
  displayLogo = true
  [navbar.logo]
    path = "tamarackdb-logo.png"
    link = "/"
    width = 128
    height = 24

[page]
  width = "wide"

[theme]
  default = "system"
  displayToggle = true

[footer]
  displayCopyright = true
  displayPoweredBy = false

[search]
  enable = true
  type = "flexsearch"
  [search.flexsearch]
    index = "content"
    tokenize = "forward"

[editURL]
  enable = false
